language: ruby
install:
  - bundle install --jobs=3 --retry=3
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get bitbucket.org/ww/goautoneg
  - go get github.com/garyburd/redigo/redis
rvm:
  - 2.1.1
env:
  -
  - GOSPECS=true
matrix:
  allow_failures:
    - env: GOSPECS=true
